<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Genesis</RootNamespace>
    <AssemblyName>Genesis</AssemblyName>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <UnityModules>CoreModule;IMGUIModule;TextRenderingModule</UnityModules>
    <VFETribalsDll Condition="'$(VFETribalsDll)' == ''">C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\3079786283\1.6\Assemblies\VFETribals.dll</VFETribalsDll>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    <PackageReference Include="Krafs.Publicizer" Version="2.*" PrivateAssets="all" />
    <Publicize Include="Assembly-CSharp" IncludeVirtualMembers="false" />
  </ItemGroup>
  <ItemGroup>
    <!-- VFE Tribals is a required mod -->
    <Reference Include="VFETribals">
      <HintPath>$(VFETribalsDll)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
